version: '3'

networks:
  api_network:

services:
  api:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - api_network
    ports:
      - $PORT:$PORT
    restart: always
  postgres:
    image: postgres
    networks:
      - api_network
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    logging:
      driver: json-file
      options:
        max-size: 50m
    restart: always
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    command: -p $POSTGRES_PORT

volumes:
  postgres_volume:
